{
  "comments": [
    {
      "key": {
        "uuid": "30b088be_80fbca57",
        "filename": "public/update_engine.te",
        "patchSetId": 2
      },
      "lineNbr": 40,
      "author": {
        "id": 1003966
      },
      "writtenOn": "2016-11-15T01:44:34Z",
      "side": 1,
      "message": "why?",
      "revId": "167701b27c6033411beff3842dc989b0d5e47ce3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "30b088be_e0371e3f",
        "filename": "public/update_engine.te",
        "patchSetId": 2
      },
      "lineNbr": 40,
      "author": {
        "id": 1115183
      },
      "writtenOn": "2016-11-15T01:47:07Z",
      "side": 1,
      "message": "This was a mistake, it should be update_engine, i\u0027ll fix shortly",
      "parentUuid": "30b088be_80fbca57",
      "revId": "167701b27c6033411beff3842dc989b0d5e47ce3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}