{
  "comments": [
    {
      "key": {
        "uuid": "2969a713_fcb422cf",
        "filename": "/COMMIT_MSG",
        "patchSetId": 5
      },
      "lineNbr": 7,
      "author": {
        "id": 1003966
      },
      "writtenOn": "2019-03-04T05:59:18Z",
      "side": 1,
      "message": "Please provide a more accurate commit message, with a Bug: line \n\n  Bug: 124277294",
      "revId": "c6f7997273311e3dda957120cd0170d24317e144",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "e593d444_778b5b8c",
        "filename": "public/domain.te",
        "patchSetId": 5
      },
      "lineNbr": 1048,
      "author": {
        "id": 1003966
      },
      "writtenOn": "2019-03-04T03:51:17Z",
      "side": 1,
      "message": "why is this exception needed?",
      "revId": "c6f7997273311e3dda957120cd0170d24317e144",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}