{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8929fe9c_c64deae5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1561651
      },
      "writtenOn": "2023-03-27T04:20:07Z",
      "side": 1,
      "message": "I went for adding the exception to isolated_compute_app (instead of reverting) as I think this is probably something that should be removed eventually.",
      "revId": "e9ac9ce0f3ebd84adc5f2e846dee427bac6bfbc1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}