{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "4943c104_43c2f0fc",
        "filename": "public/domain.te",
        "patchSetId": 1
      },
      "lineNbr": 1043,
      "author": {
        "id": 1208973
      },
      "writtenOn": "2020-11-23T15:30:01Z",
      "side": 1,
      "message": "What exactly is this?  Why is a new Treble exception needed here?",
      "revId": "eb7effe749815dbab17880f102c8d5efc4b39b1e",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}